name: witch_test
version: 0.0.1
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  benchmark_harness: any
  browser: '>=0.10.0 <0.11.0'
  umiuni2d:
    path: ../../
  dart_to_js_script_rewriter: ^0.1.0
  flutter: any
  sky: any
  sky_tools: any
  vector_math: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
transformers:
- dart_to_js_script_rewriter
dependency_overrides:
  flutter:
    path: /Users/kiyohiro/tools/git/flutter_master/packages/flutter
