name: umiuni2d
version: 0.0.1
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  benchmark_harness: any
  flutter: any
  sky: any
  sky_tools: any
  vector_math: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
dependency_overrides:
  flutter:
    path: /Users/kiyohiro/tools/git/flutter_master/packages/flutter
