name: ironheart
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  vector_math: any
  benchmark_harness: any
  umiuni2d:
    path: ../../
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
transformers:
- dart_to_js_script_rewriter